### ISSUE TITLE
base58 examples don't work

### ISSUE THREAD

**Issue by evaporei** [streamingfast/tooling#2]
As taken from the [README.md](https://github.com/streamingfast/tooling#usage):

```
to_base58 abfe0102                           # <-- As hexadecimal
5PzCau

to_base58 myname                             # <-- As string
wWsYQQr8
```

These two actually result in no output:

![スクリーンショット 2022-04-06 17 01 06](https://user-images.githubusercontent.com/15306309/162060922-f2eaa258-c75b-4336-a6c2-384515106c79.png)
![スクリーンショット 2022-04-06 17 01 23](https://user-images.githubusercontent.com/15306309/162060928-c9c274cc-1911-4aa1-bd1f-39af1a821c10.png)

I've created a Pull Request to fix a few other examples for other commands: https://github.com/streamingfast/tooling/pull/1

**Comment by evaporei** [comment]
Also, I've tried using standard input and it didn't work either 😢

**Comment by maoueh** [comment]
Really strange, works here!

![image](https://user-images.githubusercontent.com/123014/162063099-aac34755-736f-4b62-b3a1-46f260e17a3f.png)

**Comment by evaporei** [comment]
I'm running this on an Apple M1 first generation (13" I think), what computer are you using? 🤔

**Comment by maoueh** [comment]
Apple M1 Max latest generation, the problem seems rather weird since you have no input at all for most the tries that you did.

I'll check later what could cause this and will run this by you when I have some hypothesis.

**Comment by maoueh** [comment]
Fixed on latest code path. Not sure what the problem was actually, I refactored completely the `to_base58` implementation copying over the code from `to_hex`. A colleague of mine who had the same problem as you reported that it's working now.

@evaporei Please report if it's still a problem on latest branch.

**Comment by evaporei** [comment]
It works now @maoueh ! 🎉 
Thanks!!!

For whoever is trying to run the examples of this issue, on the second one remember to use `-s`, like the new `README.md`/documentation explains.
